function prc
    fig = figure(
      'Visible', 'on', ...
      'Position', [0, 0, 800, 500], ...
      'Name', 'ASIC UI', ...
      'NumberTitle', 'off'
    );
        
    % header
    uicontrol(
      'Parent', fig, ...
      'Style', 'text', ...
      'Position', [0, 400, 800, 100], ...
      'String', 'Polos, raices y ganancia', ...
      'FontSize', 15
    );

    % polos label    
    uicontrol(
      'Parent', fig, ...
      'Style', 'text', ...
      'Position', [20, 350, 150, 30], ...
      'String', 'Ingrese polos', ...
      'FontSize', 10
    );
    
    % polos input
    uicontrol(
      'Parent', fig, ...
      'Style', 'edit', ...
      'Tag', 'polesinput', ...
      'Position', [170, 350, 200, 30]
    );

    % ceros label  
    uicontrol(
      'Parent', fig, ...
      'Style', 'text', ...
      'Position', [420, 350, 150, 30], ...
      'String', 'Ingrese ceros', ...
      'FontSize', 10
    );
    
    % ceros input
    uicontrol(
      'Parent', fig, ...
      'Style', 'edit', ...
      'Tag', 'zeroesinput', ...
      'Position', [570, 350, 200, 30]
    );
    
    % ganancia label    
    uicontrol(
      'Parent', fig, ...
      'Style', 'text', ...
      'Position', [20, 290, 150, 30], ...
      'String', 'Ingrese ganancia', ...
      'FontSize', 10
    );
    
    % ganancia input
    uicontrol(
      'Parent', fig, ...
      'Style', 'edit', ...
      'Tag', 'gaininput', ...
      'Position', [170, 290, 200, 30]
    );
        
    % plot button
    plotbtn = uicontrol(
      'Style', 'pushbutton', ...
      'Position', [350, 140, 100, 30], ...
      'String', 'Plot', ...
      'Callback', @plot_prc
    );  
end

function plot_prc(hObject, eventdata)
    zeroeshandler = findobj('Tag', 'zeroesinput');
    poleshandler = findobj('Tag', 'polesinput');
    gainhandler = findobj('Tag', 'gaininput');
    zeroesstr = get(zeroeshandler, 'string');
    polesstr = get(poleshandler, 'string');
    gainstr = get(gainhandler, 'string');
    
    zeroes = str2num(zeroesstr);
    poles = str2num(polesstr);
    gain = str2num(gainstr);
    
    transf = zpk(zeroes, poles, gain)
    [zeroes, poles, gain]
    stable = isstable(transf)
    %s = -10 : 0.1 : 10;
    %plot(s, sys(s))
    %pzmap(transf)
end
